version: '3.8'

services:
  mysql:
    image: mysql:8.0.5
    container_name: mysql_review_product
    environment:
      MYSQL_ROOT_PASSWORD: super-secret-123@
      MYSQL_DATABASE: review_product
    ports:
      - "330:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - review_network

networks:
  review_network:
    driver: bridge

volumes:
  mysql_data:
